name: ChatProto GitHub Actions for Development
run-name: ChatProto GitHub Actions for Development
on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ChatProto
        run: |
          cd ${{ github.workspace }}
          pip install --upgrade pip
          pip install -e .

      - name: Test ChatProto
        run: |
          cd ${{ github.workspace }}
          python -m unittest discover ChatProto/tests
